# Generated by Django 3.1.1 on 2020-09-26 12:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20200922_1047'),
        ('feed', '0003_feed_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('parent', models.CharField(default='feed', max_length=120, verbose_name='parent')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='timestamp')),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feed')),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
