# Generated by Django 3.1.1 on 2020-09-26 05:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_creator'),
        ('like', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='parent',
            field=models.CharField(default='feed', max_length=120, verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='like',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='like',
            name='feed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feed'),
        ),
    ]
