# Generated by Django 3.1.1 on 2020-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=240, verbose_name='userName')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('profileImageUrl', models.CharField(blank=True, max_length=400, null=True, verbose_name='profileImageUrl')),
                ('firstName', models.CharField(blank=True, max_length=240, null=True, verbose_name='firstName')),
                ('lastName', models.CharField(blank=True, max_length=240, null=True, verbose_name='lastName')),
                ('phoneNo', models.CharField(blank=True, max_length=10, null=True, verbose_name='phoneNo')),
            ],
        ),
    ]
