# Generated by Django 3.1.1 on 2020-09-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
