# Generated by Django 3.1.1 on 2020-09-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='userId',
            new_name='user',
        ),
    ]
