# Generated by Django 3.1.1 on 2020-09-28 15:14

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=240, verbose_name='name')),
                ('location', models.CharField(max_length=480, verbose_name='location')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='cost')),
                ('elevation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='elevation')),
                ('isUWHS', models.BooleanField(default=False, verbose_name='isUWHS')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='population')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='timestamp')),
            ],
        ),
    ]
