# Generated by Django 3.1.1 on 2020-09-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeType',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='type'),
        ),
    ]
