# Generated by Django 3.1.1 on 2020-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_place_placetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
