export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_AUTO_LOGIN = 'AUTH_AUTO_LOGIN';

export const CURRENT_USER = 'CURRENT_USER';
export const ALL_USERS = 'ALL_USERS';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const SET_ALL_USERS = 'SET_ALL_USERS';

export const INIT_POSTS = 'INIT_POSTS';
export const SET_ALL_POSTS = 'SET_ALL_POSTS';
export const SET_POST = 'SET_POST';
export const SET_USER_POSTS = 'SET_USER_POSTS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_FAILED = 'SET_PROFILE_FAILED';

export const SET_FEED_COMMENTS = 'SET_FEED_COMMENTS';
export const SET_FEED_LATEST_COMMENTS = 'SET_FEED_LATEST_COMMENTS';
export const COMMENT_FETCH_FAIL = 'COMMENT_FETCH_FAIL';
export const COMMENT_FETCH_SUCCESS = 'COMMENT_FETCH_SUCCESS';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const SET_COMMENT_REPLIES = 'SET_COMMENT_REPLIES';
export const SET_COMMENT_LATEST_REPLIES = 'SET_COMMENT_LATEST_REPLIES';
export const REPLY_FETCH_FAIL = 'REPLY_FETCH_FAIL';
export const REPLY_FETCH_SUCCESS = 'REPLY_FETCH_SUCCESS';
export const ADD_REPLY_SUCCESS = 'ADD_REPLY_SUCCESS';
export const ADD_REPLY_FAIL = 'ADD_REPLY_FAIL';

export const LIKE_FEED = 'LIKE_FEED';
export const SET_FEED_LIKES = 'SET_FEED_LIKES';
export const SET_USER_LIKES = 'SET_USER_LIKEDS';
export const FETCH_LIKES_FAIL = 'FETCH_LIKES_FAIL';

export const SET_FOLLOWERS = 'SET_FOLLOWERS';
export const SET_FOLLOWEDS = 'SET_FOLLOWEDS';
export const FOLLOW_FETCH_FAIL = 'FOLLOW_FETCH_FAIL';

export const SET_PLACES = 'SET_PLACES';
export const FETCH_PLACES_FAIL = 'FETCH_PLACES_FAIL';
export const SET_PLACE = 'SET_PLACE';
export const FETCH_PLACE_FAIL = 'FETCH_PLACE_FAIL';