# Generated by Django 3.1.1 on 2020-09-25 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20200922_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(verbose_name='text')),
                ('status', models.CharField(default='direct', max_length=120, verbose_name='status')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='timestamp')),
                ('commentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
