# Generated by Django 3.1.1 on 2020-09-29 17:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200922_1047'),
        ('comment', '0002_comment_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('text', models.TextField(verbose_name='text')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='timestamp')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='comment.comment')),
                ('replier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
