# Generated by Django 3.1.1 on 2020-09-17 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='title')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='timestamp')),
            ],
        ),
    ]
