# Generated by Django 3.1.1 on 2020-09-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('feed', '0002_feed_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='user.profile'),
        ),
    ]
