# Generated by Django 3.1.1 on 2020-09-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_feed_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='videoUrl',
            field=models.TextField(blank=True, null=True, verbose_name='videoUrl'),
        ),
    ]
