# Generated by Django 3.1.1 on 2020-10-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feed_videourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feed_images'),
        ),
    ]
